{%- from "kubernetes/map.jinja" import common with context %}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ storageclass.name }}
  {%- if storageclass.default %}
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
  {%- endif %}
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
provisioner: kubernetes.io/{{ storageclass.provisioner}}
parameters:
  type: {{ storageclass.get('type', 'gp2') }}
